#!/bin/bash

echo ""
echo "Installing dotnet cli..."
echo ""

tools/install.sh

origPath=$PATH
export PATH="./dotnet/bin/:$PATH"

if [ $? -ne 0 ]; then
  echo >&2 ".NET Execution Environment installation has failed."
  exit 1
fi

export DOTNET_HOME="$DOTNET_INSTALL_DIR/cli"
export PATH="$DOTNET_HOME/bin:$PATH"

export autoGeneratedVersion=false

# Generate version number if not set
if [[ -z "$BuildSemanticVersion" ]]; then
    autoVersion="$((($(date +%s) - 1451606400)/60))-$(date +%S)"
    export BuildSemanticVersion="rc1-$autoVersion"
    autoGeneratedVersion=true
    
    echo "Set version to $BuildSemanticVersion"
fi

sed -i '' "s/2.0.0-*/2.0.0-$BuildSemanticVersion/g" */*/project.json 

# Restore packages and build product
dotnet restore -v Minimal # Restore all packages

# Build all
# Note the exclude: https://github.com/dotnet/cli/issues/1342
for d in src/*; do 
	echo "Building $d"
	pushd "$d"
	dotnet build
	popd
done

# Run tests
for d in test/*; do 
    echo "Testing $d"
    pushd "$d"
    dotnet test
    popd
done

sed -i '' "s/2.0.0-$BuildSemanticVersion/2.0.0-*/g" */*/project.json 

if [ $autoGeneratedVersion ]; then
    unset BuildSemanticVersion
fi

export PATH=$origPath